// Factory defaults. All money values are stored in cents.
// Line payouts multiply the line bet (bet / active lines); scatter payouts
// multiply the whole bet.

export const DEFAULT_SETTINGS = {
  siteName: 'Lucky Machines',
  currencySymbol: '$',
  startingBalance: 100000,
  allowSignup: false,
  slotsOpen: true,
  closedMessage: 'The machines are closed right now. Come back soon!',
  announcement: '',
  showLeaderboard: true,
  blackjackTable: true,
  spinDuration: 1600,
  maxAutoSpins: 50,
};

// Bumped whenever the shape of a machine config changes; older stored
// configs are replaced by the new defaults on startup (jackpots are kept).
export const MACHINE_CONFIG_VERSION = 2;

const $ = (units) => Math.round(units * 100);

export const DEFAULT_MACHINES = [
  {
    id: 'sevens',
    name: 'Lucky Sevens',
    tagline: 'The classic, now with 5 lines and wild jokers.',
    enabled: true,
    reels: 3,
    lines: 5,
    theme: { from: '#7f1d1d', to: '#f59e0b', accent: '#fde047' },
    bets: [$(1), $(2), $(5), $(10), $(25)],
    jackpotSymbol: '💎',
    wildSymbol: '🃏',
    scatterSymbol: '🔥',
    jackpotSeed: $(1000),
    jackpotContribution: 2,
    symbols: [
      { s: '🍒', name: 'Cherry', weight: 9, pays: { 2: 1.5, 3: 5 } },
      { s: '🍋', name: 'Lemon', weight: 8, pays: { 3: 8 } },
      { s: '🔔', name: 'Bell', weight: 6, pays: { 3: 13 } },
      { s: '⭐', name: 'Star', weight: 5, pays: { 3: 19 } },
      { s: '7️⃣', name: 'Seven', weight: 3, pays: { 2: 3, 3: 50 } },
      { s: '🃏', name: 'Joker (wild)', weight: 2, pays: { 3: 95 } },
      { s: '🔥', name: 'Fire (scatter)', weight: 3, pays: { 2: 0.5, 3: 3 } },
      { s: '💎', name: 'Diamond', weight: 1, pays: { 2: 16 } },
    ],
  },
  {
    id: 'fruit',
    name: 'Fruit Fiesta',
    tagline: 'Juicy little wins on every line.',
    enabled: true,
    reels: 3,
    lines: 5,
    theme: { from: '#065f46', to: '#84cc16', accent: '#fef08a' },
    bets: [$(0.5), $(1), $(2), $(5), $(10)],
    jackpotSymbol: '🍀',
    wildSymbol: '🌈',
    scatterSymbol: '🧺',
    jackpotSeed: $(500),
    jackpotContribution: 2,
    symbols: [
      { s: '🍒', name: 'Cherry', weight: 10, pays: { 2: 1.5, 3: 5 } },
      { s: '🍊', name: 'Orange', weight: 9, pays: { 2: 1, 3: 6 } },
      { s: '🍇', name: 'Grapes', weight: 7, pays: { 2: 1, 3: 10 } },
      { s: '🍉', name: 'Melon', weight: 5, pays: { 2: 1.5, 3: 16 } },
      { s: '🍓', name: 'Berry', weight: 4, pays: { 2: 2, 3: 30 } },
      { s: '🌈', name: 'Rainbow (wild)', weight: 2, pays: { 3: 80 } },
      { s: '🧺', name: 'Basket (scatter)', weight: 3, pays: { 2: 1, 3: 5 } },
      { s: '🍀', name: 'Clover', weight: 1, pays: { 2: 16 } },
    ],
  },
  {
    id: 'neon',
    name: 'Neon Nights',
    tagline: 'Nine lines under the city lights.',
    enabled: true,
    reels: 5,
    lines: 9,
    theme: { from: '#581c87', to: '#06b6d4', accent: '#f0abfc' },
    bets: [$(1), $(2), $(5), $(10), $(20)],
    jackpotSymbol: '💎',
    wildSymbol: '🌀',
    scatterSymbol: '🎤',
    jackpotSeed: $(2500),
    jackpotContribution: 2,
    symbols: [
      { s: '🎵', name: 'Beat', weight: 9, pays: { 3: 4, 4: 9, 5: 25 } },
      { s: '🍸', name: 'Cocktail', weight: 8, pays: { 3: 4, 4: 13, 5: 45 } },
      { s: '🎲', name: 'Dice', weight: 6, pays: { 3: 7, 4: 20, 5: 90 } },
      { s: '🕶️', name: 'Shades', weight: 4, pays: { 3: 13, 4: 45, 5: 220 } },
      { s: '🌀', name: 'Vortex (wild)', weight: 2, pays: { 3: 20, 4: 90, 5: 440 } },
      { s: '🎤', name: 'Mic (scatter)', weight: 2, pays: { 3: 2, 4: 9, 5: 45 } },
      { s: '💎', name: 'Diamond', weight: 3, pays: { 3: 18, 4: 130 } },
    ],
  },
  {
    id: 'pharaoh',
    name: "Pharaoh's Gold",
    tagline: 'Sun-god wilds and sacred scrolls on 9 lines.',
    enabled: true,
    reels: 5,
    lines: 9,
    theme: { from: '#78350f', to: '#eab308', accent: '#fef3c7' },
    bets: [$(2), $(5), $(10), $(25), $(50)],
    jackpotSymbol: '👑',
    wildSymbol: '🌞',
    scatterSymbol: '📜',
    jackpotSeed: $(5000),
    jackpotContribution: 3,
    symbols: [
      { s: '🐍', name: 'Cobra', weight: 9, pays: { 3: 4, 4: 9, 5: 25 } },
      { s: '🪲', name: 'Scarab', weight: 8, pays: { 3: 4, 4: 13, 5: 45 } },
      { s: '🏺', name: 'Urn', weight: 6, pays: { 3: 7, 4: 20, 5: 90 } },
      { s: '🐫', name: 'Camel', weight: 4, pays: { 3: 13, 4: 45, 5: 220 } },
      { s: '🌞', name: 'Sun god (wild)', weight: 2, pays: { 3: 20, 4: 90, 5: 440 } },
      { s: '📜', name: 'Scroll (scatter)', weight: 2, pays: { 3: 2, 4: 9, 5: 45 } },
      { s: '👑', name: 'Crown', weight: 3, pays: { 3: 20, 4: 175 } },
    ],
  },
  {
    id: 'galaxy',
    name: 'Galaxy Jackpot',
    tagline: 'Huge multipliers. Astronomical jackpot.',
    enabled: true,
    reels: 3,
    lines: 5,
    theme: { from: '#1e1b4b', to: '#7c3aed', accent: '#a5f3fc' },
    bets: [$(5), $(10), $(25), $(50), $(100)],
    jackpotSymbol: '🌟',
    wildSymbol: '🕳️',
    scatterSymbol: '🛸',
    jackpotSeed: $(10000),
    jackpotContribution: 4,
    symbols: [
      { s: '🌙', name: 'Moon', weight: 10, pays: { 3: 3 } },
      { s: '🪐', name: 'Planet', weight: 8, pays: { 3: 7 } },
      { s: '☄️', name: 'Comet', weight: 6, pays: { 3: 13 } },
      { s: '🚀', name: 'Rocket', weight: 4, pays: { 2: 1.5, 3: 35 } },
      { s: '👽', name: 'Alien', weight: 3, pays: { 2: 3, 3: 80 } },
      { s: '🕳️', name: 'Black hole (wild)', weight: 2, pays: { 3: 165 } },
      { s: '🛸', name: 'UFO (scatter)', weight: 2, pays: { 2: 0.5, 3: 8 } },
      { s: '🌟', name: 'Supernova', weight: 1, pays: { 2: 5 } },
    ],
  },
];

for (const m of DEFAULT_MACHINES) m.version = MACHINE_CONFIG_VERSION;
