// Factory defaults. All money values are stored in cents.

export const DEFAULT_SETTINGS = {
  siteName: 'Lucky Machines',
  currencySymbol: '$',
  startingBalance: 100000,
  allowSignup: false,
  slotsOpen: true,
  closedMessage: 'The machines are closed right now. Come back soon!',
  announcement: '',
  showLeaderboard: true,
  spinDuration: 1600,
  maxAutoSpins: 50,
};

const $ = (units) => Math.round(units * 100);

export const DEFAULT_MACHINES = [
  {
    id: 'sevens',
    name: 'Lucky Sevens',
    tagline: 'The classic. Three reels, big sevens.',
    enabled: true,
    reels: 3,
    theme: { from: '#7f1d1d', to: '#f59e0b', accent: '#fde047' },
    bets: [$(1), $(2), $(5), $(10), $(25)],
    jackpotSymbol: '💎',
    jackpotSeed: $(1000),
    jackpotContribution: 2,
    symbols: [
      { s: '🍒', name: 'Cherry', weight: 14, pays: { 2: 2, 3: 6 } },
      { s: '🍋', name: 'Lemon', weight: 12, pays: { 3: 10 } },
      { s: '🔔', name: 'Bell', weight: 8, pays: { 3: 25 } },
      { s: '⭐', name: 'Star', weight: 5, pays: { 2: 4, 3: 50 } },
      { s: '7️⃣', name: 'Seven', weight: 3, pays: { 2: 10, 3: 150 } },
      { s: '💎', name: 'Diamond', weight: 2, pays: { 2: 10 } },
    ],
  },
  {
    id: 'fruit',
    name: 'Fruit Fiesta',
    tagline: 'Juicy little wins, all the time.',
    enabled: true,
    reels: 3,
    theme: { from: '#065f46', to: '#84cc16', accent: '#fef08a' },
    bets: [$(0.5), $(1), $(2), $(5), $(10)],
    jackpotSymbol: '🍀',
    jackpotSeed: $(500),
    jackpotContribution: 2,
    symbols: [
      { s: '🍒', name: 'Cherry', weight: 12, pays: { 2: 2, 3: 8 } },
      { s: '🍊', name: 'Orange', weight: 10, pays: { 2: 1, 3: 10 } },
      { s: '🍇', name: 'Grapes', weight: 8, pays: { 2: 2, 3: 18 } },
      { s: '🍉', name: 'Melon', weight: 6, pays: { 2: 3, 3: 30 } },
      { s: '🍓', name: 'Berry', weight: 4, pays: { 2: 4, 3: 60 } },
      { s: '🍀', name: 'Clover', weight: 2, pays: { 2: 10 } },
    ],
  },
  {
    id: 'neon',
    name: 'Neon Nights',
    tagline: 'Five reels under the city lights.',
    enabled: true,
    reels: 5,
    theme: { from: '#581c87', to: '#06b6d4', accent: '#f0abfc' },
    bets: [$(1), $(2), $(5), $(10), $(20)],
    jackpotSymbol: '💎',
    jackpotSeed: $(2500),
    jackpotContribution: 2,
    symbols: [
      { s: '🎵', name: 'Beat', weight: 10, pays: { 3: 4, 4: 12, 5: 40 } },
      { s: '🍸', name: 'Cocktail', weight: 8, pays: { 3: 8, 4: 20, 5: 80 } },
      { s: '🎲', name: 'Dice', weight: 6, pays: { 3: 12, 4: 40, 5: 150 } },
      { s: '🕶️', name: 'Shades', weight: 4, pays: { 2: 2, 3: 25, 4: 100, 5: 500 } },
      { s: '💎', name: 'Diamond', weight: 4, pays: { 2: 3, 3: 30, 4: 200 } },
    ],
  },
  {
    id: 'pharaoh',
    name: "Pharaoh's Gold",
    tagline: 'Dig deep for the crown of the Nile.',
    enabled: true,
    reels: 5,
    theme: { from: '#78350f', to: '#eab308', accent: '#fef3c7' },
    bets: [$(2), $(5), $(10), $(25), $(50)],
    jackpotSymbol: '👑',
    jackpotSeed: $(5000),
    jackpotContribution: 3,
    symbols: [
      { s: '🐍', name: 'Cobra', weight: 10, pays: { 3: 4, 4: 10, 5: 40 } },
      { s: '🪲', name: 'Scarab', weight: 8, pays: { 3: 6, 4: 20, 5: 80 } },
      { s: '🏺', name: 'Urn', weight: 6, pays: { 3: 12, 4: 40, 5: 200 } },
      { s: '🐫', name: 'Camel', weight: 5, pays: { 2: 2, 3: 20, 4: 80, 5: 400 } },
      { s: '👑', name: 'Crown', weight: 4, pays: { 2: 4, 3: 40, 4: 250 } },
    ],
  },
  {
    id: 'galaxy',
    name: 'Galaxy Jackpot',
    tagline: 'Rare wins. Astronomical jackpot.',
    enabled: true,
    reels: 3,
    theme: { from: '#1e1b4b', to: '#7c3aed', accent: '#a5f3fc' },
    bets: [$(5), $(10), $(25), $(50), $(100)],
    jackpotSymbol: '🌟',
    jackpotSeed: $(10000),
    jackpotContribution: 4,
    symbols: [
      { s: '🌙', name: 'Moon', weight: 14, pays: { 3: 4 } },
      { s: '🪐', name: 'Planet', weight: 10, pays: { 3: 10 } },
      { s: '☄️', name: 'Comet', weight: 7, pays: { 2: 2, 3: 25 } },
      { s: '🚀', name: 'Rocket', weight: 4, pays: { 2: 6, 3: 100 } },
      { s: '👽', name: 'Alien', weight: 3, pays: { 2: 10, 3: 200 } },
      { s: '🌟', name: 'Supernova', weight: 2, pays: { 1: 1, 2: 25 } },
    ],
  },
];
